name: Deploy geoapi-server (to get latest MaxMind DBs)

on:
  workflow_dispatch:
  schedule:
    # run every Wednesday at 12 minutes past one o'clock in the morning
    - cron: "12 1 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: heroku/nodejs
          buildpack: https://github.com/mantisadnetwork/heroku-buildpack-maxmind.git
